services:
  events:
    user: root
    image: ghcr.io/ogrodje/ogrodje-events:latest
    ports:
      - "0.0.0.0:3000:7006"

    environment:
      HYGRAPH_ENDPOINT: ${HYGRAPH_ENDPOINT}
      DATABASE_URL: jdbc:sqlite:/data/ogrodje_events.db
      SENTRY_DNS: ${SENTRY_DNS}
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
      SENTRY_ENVIRONMENT: development
      SYNC_DELAY: 10 minutes

