services:
  events:
    user: root
    image: ghcr.io/ogrodje/ogrodje-events:latest
    ports:
      - "0.0.0.0:3000:7006"

    environment:
      HYGRAPH_ENDPOINT: ${HYGRAPH_ENDPOINT}
      DATABASE_URL: jdbc:sqlite:/data/ogrodje_events.db
      SENTRY_DNS: ${SENTRY_DNS}
      SENTRY_AUTH_TOKEN: ${SENTRY_AUTH_TOKEN}
      SENTRY_ENVIRONMENT: development
      SYNC_DELAY: 10 minutes

  pg:
    image: postgres:16
    restart: always
    ports:
      - "0.0.0.0:5438:5432"
    environment:
      POSTGRES_DB: "og_events"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

