services:
  events:
    volumes:
      - events-db:/data
    environment:
      SENTRY_ENVIRONMENT: production
      SYNC_DELAY: 1 hour

volumes:
  events-db:
    driver: "local"
    driver_opts:
      type: none
      device: /home/oto/Projects/ogrodje-events/data
      o: bind
