services:
  events:
    restart: always
    volumes:
      - events-db:/data
    environment:
      ENVIRONMENT: production
      SENTRY_ENVIRONMENT: production
      SYNC_DELAY: 1 hour
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      TRUNCATE_ON_BOOT: "true"
  pg:
    restart: always
    volumes:
      - events-pg-db:/var/lib/postgresql/data

volumes:
  events-db:
    driver: "local"
    driver_opts:
      type: none
      device: /home/oto/Projects/ogrodje-events/data
      o: bind

  events-pg-db:
    driver: "local"
    driver_opts:
      type: none
      device: /home/oto/Projects/ogrodje-events/events-pg-db
      o: bind
